= Changelog

== NEXT

- Now gracefully fails when some artist or release path is unfortunately resolved into an existing regular file (and not a folder).
- If the artist or release folder already exists, but with a different case, this existing folder will be used.
This avoids having two different folders "artist" and "Artist" due to different spelling in different releases.
This probably also avoids problems on Windows systems.
- In the `bandcamp-collection-donwloader.cache` file, we now save a description of the release in addition to the release ID.
This makes the cache file human-readable, and makes it possible to remove a release from the list to force a re-download;

== v2020-12-06

- Fix `NullPointerException` when downloading releases without any digital item (e.g. vinyl only).

== v2020-10-31 🎃

- Can now use the new firefox's profile.ini file format.


== v2020-09-20

- Switch to JDK 11
- Can handle many more special characters in the release artist or title.
- Skip if no digital item or no download url found.
- Use default release year (0000) when the item has none for some reason.
- Add cookies.txt parser (which means Chrome users can now use the tool!)
- Fix a JSON parse error occuring with strangely written release titles.

*External contributors*: thank you to Colin Diesh, CoryAlbrecht, jeyalee! 🍻


== v2020-04-17

First official release of bandcamp-collection-downloader! 🎉

*Highlights*: much clearer textual output, multithreaded downloads, and faster detection of already downloaded albums.

*External contributors*: thank you to barbeque-squared! 🍻

