= Changelog

== Next release

- Fix wrong logic when finding existing release or artist folders − thank you to *donaldinho*!
- Replace suggested use of the _cookies.txt_ Chrome extension with the _Get cookies.txt LOCALLY_ extension − thank you to *Skoddiethecat*!


== v2021-12-05 🎄️ 

- Add `--dry-run` option to run as normal but without writing anything to the filesystem. 
- Add a test case that uses a real bandcamp account called _bcdtest_ which owns one item.  
- Add option to skip items marked as "hidden" in the Bandcamp collection − thank you to *julien-leclercq* for the help! 🍻
- Remove option `--skip-failed-releases` / `-e`, as the current implementation does not take it into account anyway.
- Fix a bug occurring when the downloader tries to unzip single tracks while `download_type` item is missing from item data − thank you to *karlreingit* for the fix! 🍻
- When using Firefox as a source for cookies, only use cookies not find in "container tabs" (Future work: allow container tabs, but give a way to choose which ones?).
- Refactor code: split in packages, and add `IO` interface to isolate IO in a single object.
- Bump mosts dependencies, including _picocli_ now in version 4.6.1.
- Minor improvements made to the CLI because of _picocli_ 4.6.1.

== v2020-12-15

- Now gracefully fails when some artist or release path is unfortunately resolved into an existing regular file (and not a folder).
- If the artist or release folder already exists, but with a different case, this existing folder will be used.
This avoids having two different folders "artist" and "Artist" due to different spelling in different releases.
This probably also avoids problems on Windows systems.
- In the `bandcamp-collection-donwloader.cache` file, we now save a description of the release in addition to the release ID.
This makes the cache file human-readable, and makes it possible to remove a release from the list to force a re-download;

== v2020-12-06

- Fix `NullPointerException` when downloading releases without any digital item (e.g. vinyl only).

== v2020-10-31 🎃

- Can now use the new firefox's profile.ini file format.


== v2020-09-20

- Switch to JDK 11
- Can handle many more special characters in the release artist or title.
- Skip if no digital item or no download url found.
- Use default release year (0000) when the item has none for some reason.
- Add cookies.txt parser (which means Chrome users can now use the tool!)
- Fix a JSON parse error occuring with strangely written release titles.

*External contributors*: thank you to Colin Diesh, CoryAlbrecht, jeyalee! 🍻


== v2020-04-17

First official release of bandcamp-collection-downloader! 🎉

*Highlights*: much clearer textual output, multithreaded downloads, and faster detection of already downloaded albums.

*External contributors*: thank you to barbeque-squared! 🍻

